displayName: Coraza WAF
runtime: wasm
type: middleware
summary: Coraza WAF http-wasm middleware
wasmPath: ./coraza-http-wasm.wasm
testData:
  directives:
    - SecRuleEngine On
    - SecDebugLog /dev/stdout
    - SecDebugLogLevel 9
    - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
