http:
  routers:
    httpbin:
      rule: PathPrefix(`/`)
      service: httpbin
      entryPoints:
        - web
      middlewares:
        - waf

  services:
    httpbin:
      loadBalancer:
        servers:
          - url: http://httpbin:8000

  middlewares:
    waf:
      plugin:
        coraza:
          directives:
            - SecRuleEngine On
            - SecDebugLog /dev/stdout
            - SecDebugLogLevel 9
            - SecRule REQUEST_URI "@streq /admin" "id:101,phase:1,log,deny,status:403"
