name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "coraza-http-wasm version"
        required: true
        type: string

env:
  GO_VERSION: "1.21.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download artifact
        run: go run mage.go downloadArtifact
        env:
          VERSION: ${{ github.event.inputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run e2e tests
        run: go run mage.go e2e

      - name: Create draft release
        run: |
          set +e
          echo "Creating release $VERSION"
          gh release create $VERSION --draft --title "$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Push build artifact to release
        run: |
          zip -j build/coraza-http-wasm-$VERSION.zip build/coraza-http-wasm.wasm LICENSE
          gh release upload $VERSION ./build/coraza-http-wasm-$VERSION.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.inputs.version }}
